language: python
python:
  - "2.7"
matrix:
  include:
    - python: "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"
sudo: false
script:
  - flake8
  - "`which trial` vxturn"
deploy:
  provider: pypi
  user: Praekelt
  password:
    secure: "TODO"
  on:
    tags: true
    all_branches: true
