language: python
python:
  - "2.7"
matrix:
  include:
    # Test on pypy without coverage, because it's unnecessary and very slow.
    - python: "pypy"
      env: PYPY_VERSION="4.0.1" NO_COVERAGE="1"
before_install:
  - if [ ! -z "$PYPY_VERSION" ]; then source utils/setup-pypy-travis.sh; fi
install:
  - "pip install -r requirements.txt"
sudo: false
script:
  - `which trial` vxturn
deploy:
  provider: pypi
  user: Praekelt
  password:
    secure: "TODO"
  on:
    tags: true
    all_branches: true
